/**
 * @param {Object} data - Data returned from an allJson static query
 * @param {Array} data.edges - Contains all of the nodes (json objects) for the specific query
 * @param {Object} data.edges[].node - The actual json object, typically generated by the CMS
 * @returns {Array} Flattened array of all nodes
 */
export default data =>
  data.edges.reduce((collection, { node }) => {
    collection.push(node);
    return collection;
  }, []);
